# Generated by Django 5.0.2 on 2024-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comments',
            field=models.CharField(default='', max_length=400),
        ),
    ]
